name: 'Terraform Apply'

on:
  push:
    branches: 
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Format and Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: 'fmt'

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with: 
          tf_actions_version: 0.14.5
          tf_actions_subcommand: 'plan'

      - name: Terraform Apply 
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.5
          tf_actions_subcommand: 'apply'
          args: -auto-approve
